version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.11-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  auth:
    build: ./services/auth
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "8001:8000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  catalog:
    build: ./services/catalog
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "8002:8000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  booking:
    build: ./services/booking
    env_file: .env
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - catalog
      - auth
    ports:
      - "8003:8000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  payment:
    build: ./services/payment
    env_file: .env
    depends_on:
      - postgres
      - redis
      - auth
      - booking
    ports:
      - "8004:8000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    build: ./services/worker
    env_file: .env
    depends_on:
      - rabbitmq
      - postgres
    restart: on-failure

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - catalog
      - booking
      - payment
    restart: always

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    restart: always

volumes:
  pgdata:
  pgadmin_data:
  prometheus_data:
  grafana_data:
