global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Auth Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Catalog Service
  - job_name: 'catalog-service'
    static_configs:
      - targets: ['catalog:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Booking Service
  - job_name: 'booking-service'
    static_configs:
      - targets: ['booking:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Payment Service
  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment:8003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Worker Service
  - job_name: 'worker-service'
    static_configs:
      - targets: ['worker:8004']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # NGINX
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 10s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-master:6379']
    scrape_interval: 10s

  # Kafka
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    scrape_interval: 10s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 10s

  # Node Exporter (if added)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s